#!/usr/bin/env python3
"""Generate Codex custom-agent TOML from canonical Architrave agents."""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class Role:
    source: str
    output: str
    name: str


ROLES = (
    Role("agents/tournament-analyst.agent.md", ".codex/agents/architrave-tournament.toml", "architrave_tournament"),
    Role("agents/adversarial-judge.agent.md", ".codex/agents/architrave-judge.toml", "architrave_judge"),
)


def parse_scalar(value: str) -> str:
    value = value.strip()
    if value.startswith('"'):
        parsed = json.loads(value)
        if not isinstance(parsed, str):
            raise ValueError("frontmatter value must be a string")
        return parsed
    if value.startswith("'") and value.endswith("'"):
        return value[1:-1].replace("''", "'")
    return value


def read_agent(path: Path) -> tuple[str, str]:
    text = path.read_text(encoding="utf-8")
    match = re.match(r"\A---\r?\n(.*?)\r?\n---\r?\n(.*)\Z", text, re.DOTALL)
    if not match:
        raise ValueError(f"{path}: missing YAML frontmatter")
    frontmatter, body = match.groups()
    fields: dict[str, str] = {}
    for line in frontmatter.splitlines():
        field = re.match(r"^(name|description):\s*(.+)$", line)
        if field:
            fields[field.group(1)] = parse_scalar(field.group(2))
    if not fields.get("description"):
        raise ValueError(f"{path}: description is required")
    return fields["description"], body.strip() + "\n"


def render(root: Path, role: Role) -> str:
    description, instructions = read_agent(root / role.source)
    quote = lambda value: json.dumps(value, ensure_ascii=False)
    return "\n".join(
        (
            "# Generated by scripts/generate-codex-agents.py; do not edit.",
            f"name = {quote(role.name)}",
            f"description = {quote(description)}",
            'model = "gpt-5.6-sol"',
            'model_reasoning_effort = "max"',
            'sandbox_mode = "read-only"',
            f"developer_instructions = {quote(instructions)}",
            "",
        )
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parent.parent)
    args = parser.parse_args()
    root = args.root.resolve()
    stale: list[str] = []
    for role in ROLES:
        output = root / role.output
        expected = render(root, role)
        if args.check:
            if not output.exists() or output.read_text(encoding="utf-8") != expected:
                stale.append(role.output)
        else:
            output.parent.mkdir(parents=True, exist_ok=True)
            output.write_text(expected, encoding="utf-8", newline="\n")
            print(f"generated {role.output}")
    if stale:
        print("generated Codex agents are stale: " + ", ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())